<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>资产管理系统</title>
        <link rel="shortcut icon" type="image/x-icon" href="/imgs/yen-coins.png"/>
        <link rel="stylesheet" type="text/css" href="/css/base.css"/>
        <link rel="stylesheet" type="text/css" href="/css/index.css"/>
        <link rel="stylesheet" type="text/css" href="/css/sh/shCore.css"/>
        <link rel="stylesheet" type="text/css" href="/css/sh/shCoreDefault.css"/>
        <link rel="stylesheet" type="text/css" href="/css/sh/shThemeDefault.css"/>

        <link rel="stylesheet" type="text/css" href="/css/flexTab.css"/>
        <link rel="stylesheet" type="text/css" href="/css/baseTable.css"/>
        <link rel="stylesheet" type="text/css" href="/css/calendar.css"/>
        <link rel="stylesheet" type="text/css" href="/css/loading.css"/>
    </head>
    <body>
        <div class="g-container">
            <header class="g-header">
                <!--滑动导航开始-->
                <nav class="navigation in_left">
                    <div class="shiftKnob">
                        <div class="toggle"></div>
                    </div> 
                    <ul class="hidden u-navList">
                        <li data-page = "flexTab">资产售卖进度</li>
                        <li data-page = "basic">资产基础信息</li>
                        <li data-page = "makeLoans">放款统计</li>
                        <li data-page = "laterPeriodCosts">资产后期费用</li>
                    </ul>
                </nav>
                <!--滑动导航结束-->
                <h2 class="in_left h2">资产管理系统</h2>
                <!--右侧登录开始-->
                <ul class="in_right login">
                    <li>欢迎您：</li>
                    <li><a href="javascript:;" id="fuser"></a></li>
                     <li><a href="javascript:;" onclick="exit()">退出登录</a></li>
                </ul>
                <!--右侧登录结束-->
            </header>
            <section class="g-content">
                <!--<article class="flexTab"></article>
                <article class="basic"></article>
                <article class="makeLoans"></article>-->
            </section>
        </div>
        <article class="particular">
            <section class="Auto particular-content">
                <div class="particular-tab">
                    <table border="1" cellspacing="1" cellpadding="1">
                    </table>
                </div>
            </section>
        </article>
        <!-- 日期选项 -->
        <div id="date-query">
            <form >
                <section class="u-datails">
                    <input type="radio" class="query" value="" name="dates" checked/>
                    <div class="datails date-datails">
                        <input type="text" placeholder="请输入查询信息"/>
                        <h6 style="font-size: 12px;color: red;opacity: .5;"><i style="font-size: 16px;vertical-align: middle;">*     </i>此项为模糊搜索</h6>
                    </div>
                </section>
                <hr/>
                <section class="u-datails">
                    <input type="radio" class="query" value="" name="dates"/>
                    <div class="datails">
                        <input type="text" class="queryDate" placeholder="请输入成立日期" disabled/>
                    </div>
                </section>
                <hr/>
                <section class="u-datails">
                    <input type="radio" class="query" value="" name="dates"/>
                    <div class="datails">
                        <input type="text" class="queryDate" placeholder="请输入募集开始时间" disabled/>
                        <input type="text" class="queryDate" placeholder="请输入募集结束时间" disabled/>
                    </div>
                </section>
                <hr/>
                <section class="u-datails">
                    <input type="radio" class="query" value="" name="dates"/>
                    <div class="datails">
                        <input type="text" class="queryDate" placeholder="请输入售卖开始时间" disabled/>
                        <input type="text" class="queryDate" placeholder="请输入售卖结束时间" disabled/>
                        <h6 style="font-size: 12px;color: red;opacity: .5;">售卖时间格式为：YYYY-MM-DD HH</h6>
                    </div>
                </section>
                <input type="button" value="提交" class="submit" style="cursor: pointer;"/>
            </form>
        </div>
        <!-- 数据条数显示  -->
        <p id="data-item">数据加载完成，共<span></span>条<b style="color: red;padding: 0 5px;">*</b><i style="color: red;">全量数据</i></p>
        <!-- 表单名  -->
        <p id="formName"></p>
    </body>
    <script type="text/javascript" charset="utf-8" src="/js/jquery.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/jquery.cookie.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/compatibility.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/sh/shCore.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/sh/shAutoloader.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/sh/shBrushSql.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/sh/jquery.zclip.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/index.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/click.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/copyTAB.js"></script>
    <script type="text/javascript" charset="utf-8" src="/js/querySubmit.js"></script>
</html>
