<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>数据系统</title>
		<link rel="stylesheet" type="text/css" href="/css/base.css"/>
		<link rel="stylesheet" type="text/css" href="/css/index.css"/>
		<link rel="stylesheet" href="/css/demo.css">
    	<script src="/js/iconfont.js"></script>
    	<script type="text/javascript" src="/js/viewport.js"></script>
	</head>
	<body style="min-height: 400px;">
		<header  class="index-g-head">
			<h1 class="head-title">数据系统
				<aside class="head-title-user">
					<ul>
						<li style="text-align: left;">大数据 &nbsp;></li>
						<li>
							<svg class="icon" aria-hidden="true" style="color: #fff;">
		                        <use xlink:href="#icon-man"></use>
		                    </svg>
							用户  :
						</li>
						<li id="userName">游客XXX</li>
						<li id="removeCookie">退出</li>
					</ul>
				</aside>
			</h1>
		</header>
		<section class="index-g-container">
			<aside class="container-m-nav">
				<nav class="aside-nav">
					<ul class="nav-itmes">
						<li>
							 <svg class="icon asideIcon" aria-hidden="true">
		                        <use xlink:href="#icon-shouyeshouye"></use>
		                    </svg>
							<a href="javascript:;">首页概览</a>
							<svg class="icon arrow" aria-hidden="true">
		                        <use xlink:href="#icon-chevron-copy-copy-copy-copy-copy-copy"></use>
		                    </svg>
		                    <ul class="secondLevelNav">
		                    	<li>
		                    		<svg class="icon" aria-hidden="true">
				                        <use xlink:href="#icon-icondingqi"></use>
				                    </svg>
				                    <a href="javascript:;" data-state = "定期" data-title="首页 > 定期">定期</a>
		                    	</li>
		                    	<li>
		                    		<svg class="icon" aria-hidden="true">
				                        <use xlink:href="#icon-huoqibao"></use>
				                    </svg>
				                    <a href="javascript:;" data-state = "活期" data-title="首页 > 活期">活期</a>
		                    	</li>
		                    </ul>
						</li>
						<li>
							<a href="javascript:;" data-state = "海航" data-title="海航">海航</a>
							<svg class="icon arrow" aria-hidden="true">
		                        <use xlink:href="#icon-chevron-copy-copy-copy-copy-copy-copy"></use>
		                    </svg>
						</li>
						<li>
							<a href="javascript:;" data-state = "绿地" data-title="绿地">绿地</a>
							<svg class="icon arrow" aria-hidden="true">
		                        <use xlink:href="#icon-chevron-copy-copy-copy-copy-copy-copy"></use>
		                    </svg>
						</li>
						<li>
							<a href="javascript:;" data-state = "陆金所" data-title="陆金所">陆金所</a>
							<svg class="icon arrow" aria-hidden="true">
		                        <use xlink:href="#icon-chevron-copy-copy-copy-copy-copy-copy"></use>
		                    </svg>
						</li>
						<li>
							<svg class="icon asideIcon" aria-hidden="true">
		                        <use xlink:href="#icon-jijingaikuang"></use>
		                    </svg>
							<a href="javascript:;"  data-state = "历史最高收益" data-title="历史最高收益">历史最高收益</a>
							<svg class="icon arrow" aria-hidden="true">
		                        <use xlink:href="#icon-chevron-copy-copy-copy-copy-copy-copy"></use>
		                    </svg>
						</li>
					</ul>
				</nav>
			</aside>
			<article class="contentBox">
				<section class="index-content">
					<h3 class="Position-title">
						<i>首页 > 定期</i>
						<a href="javascript:;" id="getDate" class="getDate">
							<svg class="icon" aria-hidden="true" style="transform: scale(1.3);">
		                        <use xlink:href="#icon-shijian"></use>
		                    </svg>
							数据获取时间：<span style="color: #FFC107;" id="crawlerTime">2017-03-31 16:47:44.629</span>
						</a>
					</h3>
					<section class="article-content">
						<!-- start table head -->
				        <div class="table-head">
					        <table>
				                <colgroup>
					                <col />
					                <col />
					                <col />
					                <col />
					                <col />
					            </colgroup>
					            <tbody>
					            	<tr>
					                	<th>产品名称</th>
					                	<th style="position: relative;">预期年化收益 
					                		<div class="sort">
					                			<a href="javascript:;" class="ascending">
					                				<svg class="icon arrow" aria-hidden="true">
								                        <use xlink:href="#icon-chevron-copy-copy-copy-copy-copy-copy"></use>
								                    </svg>
					                			</a>
							                    <a href="javascript:;" class="invertedOrder">
							                    	<svg class="icon arrow" aria-hidden="true">
								                        <use xlink:href="#icon-chevron-copy-copy-copy-copy-copy-copy"></use>
								                    </svg>
							                    </a>
					                		</div>
			                			</th>
					                	<th>投资期限</th>
					                	<th>起投金额（元）</th>
					                	<th>进度</th>
					                </tr>
					            </tbody>
					            
				            </table>
					    </div>
					    <!-- end table head -->
					    <!-- start table body -->
				     	<div class="table-body">
					     	<table>
					            <colgroup>
					            	<col />
					                <col />
					                <col />
					                <col />
					                <col />
					            </colgroup>
					            <tbody>
					            </tbody>
					   		</table>
				    	</div>
				    	<!-- end table body -->
					</section>
				</section>
			</article>
		</section>
		<footer  class="index-g-footer"></footer>
	</body>
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/index.js"></script>
</html>
